config/routes.rb
Rails.application.routes.draw do

  root 'albums#index'

  resources :users, except: [:index] do
    resources :albums
  end

  resources :albums do
    resources :pages
  end

  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete 'signout' => 'sessions#destroy'

end

app/models/album.rb
class Album < ActiveRecord::Base

  has_many :pages, dependent: :destroy
  belongs_to :user

  validates :title, presence: true

end

app/models/page.rb
class Page < ActiveRecord::Base

  belongs_to :album

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :albums, dependent: :destroy
  has_many :pages, through: :albums

  before_create :create_remember_token
  before_save :normalize_fields

  validates :first_name,
    presence: true,
    length: { maximum: 60 }

  validates :last_name,
    presence: true,
    length: { maximum: 60 }

  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }


  validates :password,
    length: { minimum: 8 }

  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token
  end

  def normalize_fields
    self.email.downcase!
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :find_user, only: [:new, :create]

  def index
    # makes all Albums available to be grabbed by the view.
    @albums = Album.all

    # This controls the background of the landing page.
    @img_select = ['pulpfiction.gif', 'coffeeshop.gif', 'strangelove.gif', 'peek.gif', 'lolita.gif'].sample
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.create(album_params)
    redirect_to @album
  end

  def show
    @album = Album.find(params[:id])
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def album_params
    params.require(:album).permit(:title, :style, :user_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_album, only: [:index, :create]

  def index
    @pages = @album.pages.all

    #This part of the code renders
    if @pages
      render json: @pages
    else
      render status: 400, nothing: true
    end
  end

  def create
    @page = Page.create(page_params)
    @page.album_id = params["album_id"]
    if @page.save
      redirect_to @page
    else
      redirect_to @album
    end
  end

  def show
    @page = Pages.find(params[:id])

    if @page
      render json: @page
    else
      render status: 400, nothing: true
    end
  end

  private

  def find_album
    @album = Album.find(params[:album_id])
  end

  def page_params
    params.require(:page).permit(:title, :story, :video_url, :audio_url)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url
    else
      flash[:error] = 'Invalid email/password. Please try again.'
      redirect_to signin_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user, only: [:edit]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @user_albums = @user.albums
  end

  def edit
  end

  private

  def require_current_user
    if !current_user?(@user)
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Current User methods:
  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    current_user == user
  end

  #Sign in status methods
  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  #Location management
  def store_location
    if request.get?
      session[:return_to] = request.url
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
end

app/views/albums/_form.html.erb
<p><%= form_for [@user, @album] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, id: 'Playbook Title' %>

  <%= f.label :style %>
  <%= f.select :style, options_for_select([['Stylish', 'stylish'], ['Comic Book', 'comic'], ['Space', 'space'], ['Dark', 'dark']], id: 'Styles for text') %>

  <%= f.label :user_id %>
  <%= f.hidden_field :user_id, :value => @user.id %>

  <%= f.submit 'Submit', id: 'submit' %>
<% end %></p>

app/views/albums/index.html.erb
<h1>&#9658; Playbooks</h1>
<ul class="playbooks">
<% @albums.each do |album| %>
  <li>
    <%= link_to "#{album.title}", album_path(album) %>
    <% if @current_user == @album_user %>
<!--       < form_for album, method: delete do |f| >
        < f.submit "delete this PlayBook?" >
      < end > -->
    <% end %>
  </li>
<% end %>
</ul>

<%= image_tag(@img_select) %>
<!-- <video src="assets/videos/killparis.mp4" autoplay="true" id="index-vid"></video> -->

app/views/albums/new.html.erb
<h1>Create new Playbook</h1>

<%= render "form" %>

app/views/albums/show.html.erb
<div id="page-add"></div>

<div id="page-detail"></div>

<ul class="album-pages" id="album-pages"></ul>

<%= requirejs_include_tag %>
<script>
  require.config({urlArgs: 'bust='+ Date.now()});
  require(['main']);
</script>

app/views/common/_navbar.html.erb
<li>
  <span class="title">
    &#9658;<%= link_to "PlayBook", root_path %>
  </span>
</li>

app/views/common/_signout.html.erb
<% if signed_in? %>

  <li><%= form_for :session, url: signout_path, method: 'delete' do |f| %>
    Hello, <%= link_to current_user.first_name, current_user %>
    <%= f.submit "Sign out", id:'sign out' %>
  <% end %></li>


<% else %>

  <li><%= link_to "Sign in", signin_path %></li>
  <li> | </li>
  <li><%= link_to "Sign up", signup_path %></li>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlayBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <div class="navbar">
      <ul>
        <%= render 'common/signout' %>
        <%= render 'common/navbar' %>
      </ul>
    </div>

    <div class="main" role="main">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/users/_user_form.html.erb
<%= form_for @user do |f| %>
  <p><%= f.label :first_name %>
  <%= f.text_field :first_name %></p>

  <p><%= f.label :last_name %>
  <%= f.text_field :last_name %></p>

  <p><%= f.label :email %>
  <%= f.text_field :email %></p>

  <p><%= f.label :password %>
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation, 'Confirm Password' %>
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.submit "Submit", id: 'submit' %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign up for PlayBook</h1>
<p>Join to make your own playbooks for the world to see!</p>

<%= render 'user_form' %>

app/views/users/show.html.erb
<h1><%= @user.first_name %>'s Playbooks</h1>

<% if @user_albums.empty? %>
  <p>There doesn't seem to be anything here...</p>
<% else %>
  <ul>
    <% @user_albums.each do |album| %>
      <li><%= link_to album.title, album_path(album) %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to "Create new album", new_user_album_path(@user) %>